### ISSUE TITLE
大佬想请问下这个问题如何解决

### ISSUE THREAD

**Issue by Tukimi777** [AreCie/Apex_Tool#10]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Waitrose2\zhenxun_bot-0.1.6.3\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\Desktop\Waitrose2\zhenxun_bot-0.1.6.3\plugins\Apex_Tool\__init__.py", line 108, in _
    await bot.send_group_msg(group_id=event.group_id, message=f"出错啦!\n错误信息：{e}")
AttributeError: 'PrivateMessageEvent' object has no attribute 'group_id'

**Comment by AreCie** [comment]
是不是私聊Bot时出错的？私聊的话还没做，等下我加上。

**Comment by AreCie** [comment]
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\Waitrose2\zhenxun_bot-0.1.6.3\bot.py", line 21, in nonebot.run() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot__init__.py", line 261, in run get_driver().run(*args, **kwargs) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run uvicorn.run( File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\uvicorn\main.py", line 463, in run server.run() File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> 
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
> > await handler(
> > File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-BzExoYKZ-py3.9\lib\site-packages\nonebot\dependencies__init__.py", line 92, in **call**
> > return await self.call(**values)
> > File "C:\Users\Administrator\Desktop\Waitrose2\zhenxun_bot-0.1.6.3\plugins\Apex_Tool__init__.py", line 108, in _
> > await bot.send_group_msg(group_id=event.group_id, message=f"出错啦!\n错误信息：{e}")
> > AttributeError: 'PrivateMessageEvent' object has no attribute 'group_id'

已修复，直接覆盖【__init__.py】文件就行
