### ISSUE TITLE
地图轮换无法正常显示 OSError: cannot open resource

### ISSUE THREAD

**Issue by JiaHuann** [AreCie/Apex_Tool#17]
环境
- docker for windows （WSL）
- 使用zhenxun_bot 的img和配置
```shell
 priority=5, temp=False>
ZhenXun-bot  | 03-09 13:03:04 [INFO] plugins | 请求https://api.mozambiquehe.re/maprotation?auth=d7269aee4a9c956a6e96a9bc5ed428ec&version=1时返回的状态码:【200】
ZhenXun-bot  | 03-09 13:03:04 [INFO] plugins | 获取【https://api.mozambiquehe.re/maprotation?auth=d7269aee4a9c956a6e96a9bc5ed428ec&version=1】数据成功
ZhenXun-bot  | 03-09 13:03:04 [INFO] plugins | 图片【/home/zhenxun_bot/plugins/Apex_Tool/Assets/Map/broken_moon_rotation.jpg】不存在，将从【https://apexlegendsstatus.com/assets/maps/Broken_Moon.png】下载
ZhenXun-bot  | 03-09 13:03:07 [INFO] plugins | 保存成功【/home/zhenxun_bot/plugins/Apex_Tool/Assets/Map/broken_moon_rotation.jpg】
ZhenXun-bot  | 03-09 13:03:07 [INFO] nonebot | Matcher <Matcher from plugins.Apex_Tool, type=message, priority=5, temp=False> running complete
ZhenXun-bot  | 03-09 13:03:07 [ERROR] nonebot | Running matcher <Matcher from plugins.Apex_Tool, type=message, priority=5, temp=False> failed.
ZhenXun-bot  | Traceback (most recent call last):
ZhenXun-bot  |   File "/home/zhenxun_bot/bot.py", line 22, in <module>
ZhenXun-bot  |     nonebot.run()
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
ZhenXun-bot  |     get_driver().run(*args, **kwargs)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
ZhenXun-bot  |     uvicorn.run(
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
ZhenXun-bot  |     server.run()
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
ZhenXun-bot  |     return asyncio.run(self.serve(sockets=sockets))
ZhenXun-bot  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
ZhenXun-bot  |     return loop.run_until_complete(main)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
ZhenXun-bot  |     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
ZhenXun-bot  | > File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
ZhenXun-bot  |     await matcher.run(bot, event, state, stack, dependency_cache)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
ZhenXun-bot  |     await self.simple_run(bot, event, state, stack, dependency_cache)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
ZhenXun-bot  |     await handler(
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
ZhenXun-bot  |     return await self.call(**values)
ZhenXun-bot  |   File "/home/zhenxun_bot/plugins/Apex_Tool/__init__.py", line 102, in _
ZhenXun-bot  |     await addText(im, 50, GameMode_Dict[data], 20, 20)  # 地图类型
ZhenXun-bot  |   File "/home/zhenxun_bot/plugins/Apex_Tool/utils.py", line 13, in addText
ZhenXun-bot  |     typeface = ImageFont.truetype(Font_Path, size)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 959, in truetype
ZhenXun-bot  |     return freetype(font)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 956, in freetype
ZhenXun-bot  |     return FreeTypeFont(font, size, index, encoding, layout_engine)
ZhenXun-bot  |   File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 247, in __init__
ZhenXun-bot  |     self.font = core.getfont(
ZhenXun-bot  | OSError: cannot open resource
```

感谢项目维护者。

**Comment by JiaHuann** [comment]
大概有思路了，是imageFont.truetype在docker中部署解析路径的问题，如果不是在docker中使用本插件应该不会有问题，解决后我试试提个pr
