### ISSUE TITLE
输入指令后报错，麻烦看下是什么原因呢

### ISSUE THREAD

**Issue by YueLinXieK** [AreCie/Apex_Tool#7]
08-05 09:41:52 [ERROR] nonebot | Running matcher <Matcher from three_plugins.Apex_Tool, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "/home/nb-cli/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 23, in run_bot
    nonebot.run()
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/home/nb-cli/.local/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/nb-cli/.local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/home/nb-cli/.local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "./three_plugins/Apex_Tool/__init__.py", line 44, in _
    retdata = json.loads(resp.text)
  File "/usr/local/python3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AreCie** [comment]
#4 
可以参考下这个问题，一般是请求API出错了，这点我确实没做的太好，不过已经在改了，新版本马上发布。
这个问题你可以尝试再请求一次试试，如果不行，可以访问下这个链接，看看数据数据正常不`https://api.mozambiquehe.re/maprotation?auth=你申请的接口Token&version=1`

**Comment by YueLinXieK** [comment]
这个api链接访问不了
Error: API key doesn't exist !

**Comment by AreCie** [comment]
> 这个api链接访问不了 Error: API key doesn't exist !

API的密钥不存在，你申请密钥了么

**Comment by YueLinXieK** [comment]
申请了的，但是没有立即用，不至于会过期吧。。

**Comment by AreCie** [comment]
> 申请了的，但是没有立即用，不至于会过期吧。。

不会，你把密钥发我邮箱，我看下，2042642971@qq.com，或者直接回复也行

**Comment by AreCie** [comment]
![image](https://user-images.githubusercontent.com/41849402/182985999-fa99a2fa-a7c6-4cc8-8db1-7b5794ff5b4f.png)
可以请求到，没问题，你检查下填下的是不是漏了什么

**Comment by YueLinXieK** [comment]
嗯，我找到原因了，我配置有误，感谢解答

**Comment by AreCie** [comment]
> 嗯，我找到原因了，我配置有误，感谢解答

不客气
